#!python3
"""Pack header-bar PNGs into src/ui_icons.h for the e-paper framebuffer.

Each asset is thresholded to 1 bit and stored MSB-first with rows padded to a
whole byte. At paint time the set bits are drawn with the current theme ink,
so one mask works for light and dark.

    python tools/genicons.py

PNG sources live in `assets/`. `ink` is "dark" when the glyph is black on white
(settings-light, refresh-light, dark/moon) and "light" when it is white on black
(light/sun).

`size` is (w, h), or None to keep the source pixels. `crop` trims to the ink
bounding box (with 1 px padding) before packing — used for the splash wordmark.
"""

import argparse
import os
import sys

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASSETS = os.path.join(ROOT, "assets")
ICON_SIZE = 56

# name, filename, ink, size, crop
ICONS = [
    ("IconRefresh", "refresh-light.png", "dark", (ICON_SIZE, ICON_SIZE), False),
    ("IconSettings", "settings-light.png", "dark", (ICON_SIZE, ICON_SIZE), False),
    ("IconSun", "light.png", "light", (ICON_SIZE, ICON_SIZE), False),
    ("IconMoon", "dark.png", "dark", (ICON_SIZE, ICON_SIZE), False),
    ("IconBack", "back-light.png", "dark", (ICON_SIZE, ICON_SIZE), False),
    ("LogoSuperserif", "logo.png", "dark", None, True),
]


def chunks(seq, n):
    for i in range(0, len(seq), n):
        yield seq[i : i + n]


def is_ink(value, ink):
    return value > 128 if ink == "light" else value < 128


def pack_icon(path, ink, size, crop):
    image = Image.open(path).convert("RGBA")
    background = Image.new("RGBA", image.size, (255, 255, 255, 255))
    image = Image.alpha_composite(background, image).convert("L")
    if crop:
        mask = image.point(lambda p: 255 if is_ink(p, ink) else 0)
        bbox = mask.getbbox()
        if bbox:
            left, top, right, bottom = bbox
            image = image.crop((
                max(0, left - 1),
                max(0, top - 1),
                min(image.width, right + 1),
                min(image.height, bottom + 1),
            ))
    if size is not None:
        image = image.resize(size, Image.Resampling.LANCZOS)
    width, height = image.size
    if width > 255 or height > 255:
        raise SystemExit(f"{path}: {width}x{height} exceeds UiIcon uint8_t size")
    pixels = list(image.getdata())
    stride = (width + 7) // 8
    packed = bytearray(stride * height)
    ink_count = 0
    for y in range(height):
        for x in range(width):
            if is_ink(pixels[y * width + x], ink):
                packed[y * stride + (x // 8)] |= 0x80 >> (x % 8)
                ink_count += 1
    return packed, width, height, stride, ink_count


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("output", nargs="?", default=os.path.join(ROOT, "src", "ui_icons.h"))
    args = parser.parse_args()

    with open(args.output, "w", encoding="ascii", newline="\n") as out:
        out.write("// Generated by tools/genicons.py -- do not edit by hand.\n")
        out.write("// 1-bit masks, MSB first, rows padded to a byte. Ink is theme-coloured.\n")
        out.write("#pragma once\n\n")
        out.write("#include <Arduino.h>\n")
        out.write("#include <stdint.h>\n\n")
        out.write("struct UiIcon {\n")
        out.write("    uint8_t w;\n")
        out.write("    uint8_t h;\n")
        out.write("    uint8_t stride;\n")
        out.write("    const uint8_t *bits;\n")
        out.write("};\n\n")

        for name, filename, ink, size, crop in ICONS:
            path = os.path.join(ASSETS, filename)
            if not os.path.isfile(path):
                raise SystemExit(f"icon not found: {path}")
            packed, width, height, stride, ink_count = pack_icon(path, ink, size, crop)
            print(f"{name}: {width}x{height}, {ink_count} ink px, {len(packed)} bytes",
                  file=sys.stderr)
            out.write(f"const uint8_t {name}Bits[{len(packed)}] PROGMEM = {{\n")
            for chunk in chunks(packed, 16):
                out.write("    " + " ".join(f"0x{b:02X}," for b in chunk) + "\n")
            out.write("};\n")
            out.write(f"const UiIcon {name} PROGMEM = {{ {width}, {height}, {stride}, "
                      f"{name}Bits }};\n\n")

    print(f"wrote {args.output}", file=sys.stderr)


if __name__ == "__main__":
    main()
